[workspace]
resolver = "3"
members = ["fold", "anny", "ese", "sod", "examples/*", "examples/sod-demo/node"]

# hoisted from fold; applies workspace-wide
[profile.release]
opt-level = 3
codegen-units = 1
lto = "fat"

[profile.dev]
opt-level = 3 # required for reasonable ese/anny perf

# hoisted from anny
[profile.bench]
lto = "fat"
codegen-units = 1
