use std::process::Command;

#[test]
fn command_line_exposes_reproducible_demo_and_benchmark_recipes() {
    // Catches a prototype whose required evidence can only be regenerated by undocumented code changes.
    let output = Command::new(env!("CARGO_BIN_EXE_reach-rollup-lab"))
        .arg("--help")
        .output()
        .unwrap();
    assert!(output.status.success());
    let stdout = String::from_utf8(output.stdout).unwrap();
    assert!(stdout.contains("demo <evidence-dir> <temporary-dir>"));
    assert!(stdout.contains("bench-exact"));
    assert!(stdout.contains("bench-candidate"));
}

#[test]
fn command_line_rejects_unknown_mode_without_side_effects() {
    // Catches silently running an unintended expensive mode after a typo.
    let output = Command::new(env!("CARGO_BIN_EXE_reach-rollup-lab"))
        .arg("unknown")
        .output()
        .unwrap();
    assert!(!output.status.success());
    assert!(
        String::from_utf8(output.stderr)
            .unwrap()
            .contains("unknown command")
    );
}
