import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdtemp,chmod,symlink,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {Client,BogError,writePrivate,installPrivate,connect} from '../src/index.js';
const fixtures=JSON.parse(await readFile(new URL('../../fixtures/requests.json',import.meta.url),'utf8'));
test('both clients use the shared HTTP contract',async()=>{
 const received=[];const server=createServer(async(req,res)=>{const chunks=[];for await(const b of req)chunks.push(b);const raw=Buffer.concat(chunks).toString();received.push({http:req.method,path:req.url,body:raw?JSON.parse(raw):null});assert.equal(req.headers.authorization,'Bearer private');res.setHeader('Content-Type','application/json');res.end('{"ok":true}');});
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));try{const c=new Client(`http://127.0.0.1:${server.address().port}`,'private','bog');for(const f of fixtures){const name={batch_get:'batchGet',request_status:'requestStatus',preview_cleanup:'previewCleanup',execute_cleanup:'executeCleanup',delete_sandbox:'deleteSandbox'}[f.method]??f.method;assert.deepEqual(await c[name](...f.args),{ok:true});assert.deepEqual(received.at(-1),{http:f.http,path:f.path,body:f.body});}}finally{await new Promise(resolve=>server.close(resolve));}
});
test('private JSON and dotenv reject symlinks and broad permissions',async()=>{const dir=await mkdtemp(join(tmpdir(),'bog-client-'));try{for(const format of ['json','dotenv']){const p=join(dir,format);await writePrivate(p,{BOG_CLOUD_URL:'https://bog.example',BOG_CLOUD_TOKEN:'secret',BOG_ID:'bog'},format);assert.equal((await Client.fromConfig(p)).bogId,'bog');await assert.rejects(writePrivate(p,{}));await symlink(p,p+'.link');await assert.rejects(Client.fromConfig(p+'.link'));await chmod(p,0o644);await assert.rejects(Client.fromConfig(p));}}finally{await rm(dir,{recursive:true});}});
test('flat and nested auth errors are recognized without leaking bodies',async()=>{for(const error of ['authorization_pending',{code:'slow_down',message:'secret'},'access_denied',{code:'expired_token',message:'secret'}]){const server=createServer((req,res)=>{res.statusCode=400;res.end(JSON.stringify({error}));});await new Promise(r=>server.listen(0,'127.0.0.1',r));try{const c=new Client(`http://127.0.0.1:${server.address().port}`,'secret');await assert.rejects(c.request('POST','/auth/device/token',{}),e=>e instanceof BogError&&!e.message.includes('secret')&&e.code===(typeof error==='string'?error:error.code));}finally{await new Promise(r=>server.close(r));}}});
test('additive search preserves existing definition and revision',async()=>{const original={resources:{docs:{terminal:{kind:'table'}}},expose:{get:{target:'docs',action:'get'}}};const copy=structuredClone(original);const c=new Client('https://bog.example','secret','bog');const calls=[];c.request=async(...args)=>{calls.push(args);return calls.length===1?{definition:original,revision:7}:calls.length===2?{compatible:true}:{job_id:'job',status:'succeeded'};};await c.addSearch('words',['/title'],'bm25');assert.deepEqual(original,copy);assert.equal(calls[2][2].expected_revision,7);assert.deepEqual(calls[2][2].definition.resources.docs,copy.resources.docs);assert.deepEqual(calls[2][2],calls[1][2]);});
test('invalid batch and pagination fail before network access',()=>{const c=new Client('https://bog.example','secret','bog');assert.throws(()=>c.batchGet([]));assert.throws(()=>c.batchGet(Array(101).fill('a')));let body;c.query=(resource,args)=>{body=args;};c.list('docs',{after:'a',before:'z'});assert.deepEqual(body,{limit:100,after:'a',before:'z'});});
test('uncertain writes are attempted exactly once and errors are safe',async()=>{let count=0;const server=createServer((req,res)=>{count++;req.socket.destroy();});await new Promise(r=>server.listen(0,'127.0.0.1',r));try{const c=new Client(`http://127.0.0.1:${server.address().port}`,'secret','bog');await assert.rejects(c.put('key',{secret:'private'}),e=>e.message.includes('may have completed')&&!e.message.includes('private'));assert.equal(count,1);}finally{await new Promise(r=>server.close(r));}});
test('private install consumes handoff once and refuses existing output before redemption',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'bog-install-'));let redeemed=0;
 const server=createServer((req,res)=>{if(req.method==='POST'){redeemed++;res.end(JSON.stringify({bog_id:'bog',id:'credential',token:'private-app-token'}));}else res.end('{}');});await new Promise(r=>server.listen(0,'127.0.0.1',r));
 try{const base=`http://127.0.0.1:${server.address().port}`,auth=join(dir,'auth.json'),output=join(dir,'app.env');await writePrivate(auth,{origin:base,access_token:'manager',expires_at:Date.now()/1000+600});const result=await installPrivate(base,auth,'00000000-0000-0000-0000-000000000001',output,'dotenv');assert.equal(result.status,'installed');assert.ok(!JSON.stringify(result).includes('private-app-token'));assert.equal((await Client.fromConfig(output)).bogId,'bog');await assert.rejects(installPrivate(base,auth,'00000000-0000-0000-0000-000000000001',output));assert.equal(redeemed,1);}finally{await new Promise(r=>server.close(r));await rm(dir,{recursive:true});}
});
test('create options retain nonsecret handoff and confirmations gate destructive calls',async()=>{const c=new Client('https://bog.example','secret');let call;c.request=async(...args)=>{call=args;return {id:'bog',status:'starting',app_access:{handoff_id:'handoff'}};};const result=await c.create('name','stable',undefined,60,{wait:false,sandbox:true,appAccess:{scope:'read',label:'app'}});assert.equal(result.app_access.handoff_id,'handoff');assert.deepEqual(call[2],{name:'name',wait:false,sandbox:true,app_access:{scope:'read',label:'app'}});assert.throws(()=>c.deleteSandbox('other'));assert.throws(()=>c.executeCleanup('preview','other'));});
test('connect reuses matching unexpired private authorization without another approval',async()=>{const dir=await mkdtemp(join(tmpdir(),'bog-connect-'));const paths=[];const server=createServer((req,res)=>{paths.push(req.url);res.end('{}');});await new Promise(r=>server.listen(0,'127.0.0.1',r));try{const base=`http://127.0.0.1:${server.address().port}`,file=join(dir,'auth');await writePrivate(file,{origin:base,access_token:'manager',expires_at:Date.now()/1000+600});assert.deepEqual(await connect(base,file,()=>assert.fail('unnecessary approval')),{status:'connected'});assert.deepEqual(paths,['/v1/me']);await writePrivate(file,{origin:base,access_token:'replacement',expires_at:Date.now()/1000+600},'json',true);assert.equal((await Client.fromAuth(file,base)).base,base);await assert.rejects(connect('https://other.example',file));}finally{await new Promise(r=>server.close(r));await rm(dir,{recursive:true});}});
test('helper-produced dotenv preserves escaped quote and backslash without evaluation',async()=>{
 const {execFileSync}=await import('node:child_process');const dir=await mkdtemp(join(tmpdir(),'bog-helper-'));const path=join(dir,'app.env');
 try{execFileSync('python3',['-c',`import sys;sys.path.insert(0,'scripts/cloud');from bog_app_access import write_private;write_private(sys.argv[1],{'BOG_CLOUD_URL':'https://bog.example','BOG_ID':'bog','BOG_CLOUD_TOKEN':"private'\\\\$\u0060literal\u0060"},output_format='dotenv')`,path],{cwd:new URL('../../../',import.meta.url)});const c=await Client.fromConfig(path);assert.equal(c._token,"private'\\$`literal`");}finally{await rm(dir,{recursive:true});}
});
test('explicit numeric throttle guidance retries identical writes at most twice',async()=>{
 const seen=[];const server=createServer(async(req,res)=>{const chunks=[];for await(const part of req)chunks.push(part);seen.push([req.url,req.headers['idempotency-key'],Buffer.concat(chunks).toString()]);res.statusCode=seen.length<3?429:200;if(seen.length===1)res.setHeader('Retry-After','0');res.end(seen.length===1?JSON.stringify({error:{code:'rate_limited'}}):seen.length===2?JSON.stringify({error:{code:'rate_limited'},retry_after_ms:1}):'{"ok":true}');});await new Promise(r=>server.listen(0,'127.0.0.1',r));
 try{const c=new Client(`http://127.0.0.1:${server.address().port}`,'private','bog');assert.deepEqual(await c.request('PUT',c.path('/docs/key'),{value:1},'same'),{ok:true});assert.equal(seen.length,3);assert.ok(seen.every(v=>JSON.stringify(v)===JSON.stringify(seen[0])));}finally{await new Promise(r=>server.close(r));}
 for(const [status,delay,expected] of [[429,0,3],[429,null,1],[429,60000,1],[409,0,1]]){const c=new Client('https://bog.example','private','bog');let count=0;c._requestOnce=async()=>{count++;throw new BogError(status,'rate_limited',delay);};await assert.rejects(c.put('key',{value:1}));assert.equal(count,expected);}
});
